#### XGBoost

In [9]:
#install xgboost
! pip install xgboost

Defaulting to user installation because normal site-packages is not writeable
  Obtaining dependency information for xgboost from https://files.pythonhosted.org/packages/75/dd/9afe0d9d0f61a5384c3932626a022e38c396a5d88e6f5345ad2f7b576747/xgboost-1.7.6-py3-none-win_amd64.whl.metadata
   ---------------------------------------- 0.0/70.9 MB ? eta -:--:--
   ---------------------------------------- 0.1/70.9 MB 2.4 MB/s eta 0:00:30
   ---------------------------------------- 0.3/70.9 MB 3.5 MB/s eta 0:00:21
    --------------------------------------- 1.0/70.9 MB 6.9 MB/s eta 0:00:11
    --------------------------------------- 1.5/70.9 MB 8.8 MB/s eta 0:00:08
    --------------------------------------- 1.5/70.9 MB 8.8 MB/s eta 0:00:08
   - -------------------------------------- 2.4/70.9 MB 8.5 MB/s eta 0:00:09
   - -------------------------------------- 3.1/70.9 MB 9.3 MB/s eta 0:00:08
   -- ------------------------------------- 3.6/70.9 MB 9.6 MB/s eta 0:00:08
   -- -------------------------

#### import Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#### Splitting the data into the training set and the test set

In [5]:
dataset = pd.read_csv('../dataFiles/breast_cancer.csv')

x = dataset.iloc[:, :-1].values
y = dataset.iloc[: , -1].values

In [7]:
print(f'{x[:10]}\n{y[:10]}')

[[1000025       5       1       1       1       2       1       3       1
        1]
 [1002945       5       4       4       5       7      10       3       2
        1]
 [1015425       3       1       1       1       2       2       3       1
        1]
 [1016277       6       8       8       1       3       4       3       7
        1]
 [1017023       4       1       1       3       2       1       3       1
        1]
 [1017122       8      10      10       8       7      10       9       7
        1]
 [1018099       1       1       1       1       2      10       3       1
        1]
 [1018561       2       1       2       1       2       1       3       1
        1]
 [1033078       2       1       1       1       2       1       1       1
        5]
 [1033078       4       2       1       1       2       1       2       1
        1]]
[2 2 2 2 2 4 2 2 2 2]


#### Split the dataset into the Training Set and Test Set

In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)

#### Training XGBoost on the Training Set

In [14]:
from xgboost import XGBClassifier # for regression model use XGBRegressor
y_train_binary = np.where(y_train == 2, 0, 1)
# Create and fit the classifier
classifier = XGBClassifier()
classifier.fit(x_train, y_train_binary)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

#### Making the confusion Matrix

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 0  0  0  0]
 [ 0  0  0  0]
 [85  2  0  0]
 [ 1 49  0  0]]


0.0

#### Applying K-Fold Cross Validation

In [17]:
from sklearn.model_selection import cross_val_score
accuracies =cross_val_score(estimator= classifier, X =x_train, y=y_train_binary, cv=10)
print(f'Accuracy: {accuracies.mean()*100:.2f}%')
print(f'Standard Deviation: {accuracies.std()*100:.2f}%') # indicates the variance

Accuracy: 96.53%
Standard Deviation: 2.63%
